-- 008_star_schema.sql
-- Odev 3.4: analitik katman (star schema).
-- OLTP tablolari public seması altinda kalir; analitik tablolar star seması altinda.

BEGIN;

CREATE SCHEMA IF NOT EXISTS star;

-- ============================================================ dim_date
-- Grain: bir satir = bir takvim gunu.
CREATE TABLE IF NOT EXISTS star.dim_date (
    date_key     integer PRIMARY KEY,          -- YYYYMMDD
    tarih        date    NOT NULL UNIQUE,
    yil          integer NOT NULL,
    ceyrek       integer NOT NULL,
    ay           integer NOT NULL,
    ay_adi       text    NOT NULL,
    gun          integer NOT NULL,
    hafta_gunu   integer NOT NULL,             -- 0 = Pazar
    hafta_sonu   boolean NOT NULL,
    ay_basi      date    NOT NULL
);

-- ======================================================== dim_customer
-- Grain: bir satir = bir musterinin bir gecerlilik donemi (SCD2).
-- Ayni user_id icin birden cok satir olabilir; yalnizca birinde is_current = true.
CREATE TABLE IF NOT EXISTS star.dim_customer (
    customer_sk  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint      NOT NULL,          -- dogal anahtar
    email        text        NOT NULL,
    full_name    text        NOT NULL,
    country      text,
    is_active    boolean     NOT NULL,
    valid_from   timestamptz NOT NULL,
    valid_to     timestamptz,                   -- NULL = hala gecerli
    is_current   boolean     NOT NULL,

    CONSTRAINT dim_customer_donem_tutarli CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT dim_customer_current_tutarli CHECK (
        (is_current AND valid_to IS NULL) OR (NOT is_current AND valid_to IS NOT NULL)
    )
);

-- Ayni musteri icin yalnizca BIR guncel satir olabilir.
CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_customer_tek_guncel
    ON star.dim_customer (user_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_dim_customer_user ON star.dim_customer (user_id);

-- ========================================================= dim_product
-- Grain: bir satir = bir urunun guncel hali (SCD1: degisiklikler uzerine yazilir).
-- Tarihsel fiyat olgu tablosunda snapshot olarak tutuluyor (K-002), bu yuzden SCD2'ye gerek yok.
CREATE TABLE IF NOT EXISTS star.dim_product (
    product_sk    bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    bigint        NOT NULL UNIQUE,
    sku           text          NOT NULL,
    urun_adi      text          NOT NULL,
    kategori_id   bigint        NOT NULL,
    kategori_adi  text          NOT NULL,
    kok_kategori  text          NOT NULL,
    list_price    numeric(12,2) NOT NULL,
    unit_cost     numeric(12,2) NOT NULL,
    aktif         boolean       NOT NULL
);

-- ========================================================== fct_orders
-- Grain: bir satir = bir siparis.
CREATE TABLE IF NOT EXISTS star.fct_orders (
    order_id         bigint        PRIMARY KEY,     -- dejenere boyut
    customer_sk      bigint        NOT NULL REFERENCES star.dim_customer (customer_sk),
    date_key         integer       NOT NULL REFERENCES star.dim_date (date_key),
    ordered_at       timestamptz   NOT NULL,
    status           text          NOT NULL,
    shipping_country text,
    kalem_sayisi     integer       NOT NULL,
    brut_tutar       numeric(14,2) NOT NULL,
    indirim_tutar    numeric(14,2) NOT NULL,
    net_tutar        numeric(14,2) NOT NULL,
    maliyet_tutar    numeric(14,2) NOT NULL,
    brut_marj        numeric(14,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_fct_orders_date     ON star.fct_orders (date_key);
CREATE INDEX IF NOT EXISTS idx_fct_orders_customer ON star.fct_orders (customer_sk);

-- ===================================================== fct_order_items
-- Grain: bir satir = bir siparis kalemi.
CREATE TABLE IF NOT EXISTS star.fct_order_items (
    order_item_id bigint        PRIMARY KEY,
    order_id      bigint        NOT NULL REFERENCES star.fct_orders (order_id) ON DELETE CASCADE,
    customer_sk   bigint        NOT NULL REFERENCES star.dim_customer (customer_sk),
    product_sk    bigint        NOT NULL REFERENCES star.dim_product (product_sk),
    date_key      integer       NOT NULL REFERENCES star.dim_date (date_key),
    status        text          NOT NULL,
    adet          integer       NOT NULL,
    birim_fiyat   numeric(12,2) NOT NULL,
    birim_maliyet numeric(12,2) NOT NULL,
    brut_tutar    numeric(14,2) NOT NULL,
    maliyet_tutar numeric(14,2) NOT NULL,
    brut_marj     numeric(14,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_fct_items_date     ON star.fct_order_items (date_key);
CREATE INDEX IF NOT EXISTS idx_fct_items_product  ON star.fct_order_items (product_sk);
CREATE INDEX IF NOT EXISTS idx_fct_items_customer ON star.fct_order_items (customer_sk);

COMMIT;
