-- 009_dim_product_price.sql
-- Fiyat mini-boyutu (SCD2). dim_product SCD1 kalir; yalnizca hizli degisen
-- fiyat/maliyet kolonlari ayri bir SCD2 tablosunda surumlenir.
-- Grain: bir satir = bir urunun bir fiyat gecerlilik donemi.

BEGIN;

CREATE TABLE IF NOT EXISTS star.dim_product_price (
    price_sk    bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  bigint        NOT NULL,
    list_price  numeric(12,2) NOT NULL,
    unit_cost   numeric(12,2) NOT NULL,
    valid_from  timestamptz   NOT NULL,
    valid_to    timestamptz,
    is_current  boolean       NOT NULL,

    CONSTRAINT dpp_donem_tutarli CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT dpp_current_tutarli CHECK (
        (is_current AND valid_to IS NULL) OR (NOT is_current AND valid_to IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_dpp_tek_guncel
    ON star.dim_product_price (product_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS idx_dpp_urun_donem
    ON star.dim_product_price (product_id, valid_from);

COMMIT;
